# Generated by Django 3.2.4 on 2021-09-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_createtodo_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createtodo',
            name='dateTime',
        ),
    ]
