# Generated by Django 3.1.6 on 2021-09-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_remove_userinfo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
    ]
